name: Deploy Updated Quest Data

on:
  push:
    paths:
      - 'data.js'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your region
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli
      
      - name: Deploy to Amplify
        run: |
          echo "Deploying updated quest data to Amplify..."
          amplify pull --appId ${{ secrets.AMPLIFY_APP_ID }} --envName prod --yes
          amplify publish --yes
